# Railway Deployment Configuration

# This file tells Railway how to deploy your FastAPI backend

[build]
command = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn server:app --host 0.0.0.0 --port $PORT"

[env]
MONGO_URL = "REPLACE_WITH_YOUR_MONGODB_ATLAS_URL"
DB_NAME = "portfolio"